profile                      = "elastic2ls-dev"
region                       = "eu-central-1"
environment                  = "prod"
account_id                   = "YOURACCOUNTID"
project_name                 = "sample-tf-setup"